"""Processing-state port."""

from __future__ import annotations

from typing import Protocol


class StateRepository(Protocol):
    async def is_processed(self, processing_key: str) -> bool: ...
    async def mark_processed(self, processing_key: str) -> None: ...
    async def get_checkpoint(self, key: str) -> str | None: ...
    async def set_checkpoint(self, key: str, cursor: str | None) -> None: ...
